/*
Copyright(C) 2016 Interactive Health Solutions, Pvt. Ltd.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors.
 */

/**
 * @author owais.hussain@ihsinformatics.com
 */

package com.ihsinformatics.gfatmweb.shared.model;

// Generated Dec 9, 2015 9:08:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DataLog generated by hbm2java
 */
@Entity
@Table(name = "data_log", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class DataLogClient implements java.io.Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = 692186977724902027L;
	private Integer logId;
	private UsersClient users;
	private LocationClient location;
	private String logType;
	private String entityName;
	private String record;
	private String description;
	private Date dateCreated;
	private String uuid;

	public DataLogClient() {
	}

	public DataLogClient(UsersClient users, LocationClient location,
			String logType, String entityName, String record, String description) {
		this.users = users;
		this.location = location;
		this.logType = logType;
		this.entityName = entityName;
		this.record = record;
		this.description = description;
	}

	public DataLogClient(UsersClient users, LocationClient location,
			String logType, String entityName, String record,
			String description, Date dateCreated, String uuid) {
		this.users = users;
		this.location = location;
		this.logType = logType;
		this.entityName = entityName;
		this.record = record;
		this.description = description;
		this.dateCreated = dateCreated;
		this.uuid = uuid;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "log_id", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public UsersClient getUsers() {
		return this.users;
	}

	public void setUsers(UsersClient users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_at")
	public LocationClient getLocation() {
		return this.location;
	}

	public void setLocation(LocationClient location) {
		this.location = location;
	}

	@Column(name = "log_type", nullable = false, length = 6)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Column(name = "entity_name", nullable = false, length = 45)
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "record", length = 65535)
	public String getRecord() {
		return this.record;
	}

	public void setRecord(String record) {
		this.record = record;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 38)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Override
	public String toString() {
		return logId + ", " + location + ", " + logType + ", " + entityName
				+ ", " + record + ", " + description + ", " + dateCreated
				+ ", " + uuid;
	}
}
