/*
Copyright(C) 2016 Interactive Health Solutions, Pvt. Ltd.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors.
 */

/**
 * @author owais.hussain@ihsinformatics.com
 */

package com.ihsinformatics.gfatmweb.shared.model;

// Generated Dec 9, 2015 9:08:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Definition generated by hbm2java
 */
@Entity
@Table(name = "definition", uniqueConstraints = @UniqueConstraint(columnNames = "uuid"))
public class DefinitionClient implements java.io.Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = -5939762925698149246L;
	private Integer definitionId;
	private UsersClient usersByCreatedBy;
	private LocationClient locationByCreatedAt;
	private LocationClient locationByChangedAt;
	private UsersClient usersByChangedBy;
	private DefinitionTypeClient definitionType;
	private String definition;
	private String description;
	private Boolean default_;
	private Date dateCreated;
	private Date dateChanged;
	private String uuid;

	public DefinitionClient() {
	}

	public DefinitionClient(DefinitionTypeClient definitionType,
			String definition) {
		this.definitionType = definitionType;
		this.definition = definition;
	}

	public DefinitionClient(DefinitionTypeClient definitionType,
			String definition, UsersClient createdBy, Date dateCreated,
			String uuid) {
		this.definitionType = definitionType;
		this.definition = definition;
		this.usersByCreatedBy = createdBy;
		this.dateCreated = dateCreated;
		this.uuid = uuid;
	}

	public DefinitionClient(DefinitionTypeClient definitionType,
			String definition, String description, Boolean default_,
			UsersClient createdBy, LocationClient createdAt, Date dateCreated,
			String uuid) {
		this.usersByCreatedBy = createdBy;
		this.locationByCreatedAt = createdAt;
		this.definitionType = definitionType;
		this.definition = definition;
		this.description = description;
		this.default_ = default_;
		this.dateCreated = dateCreated;
		this.uuid = uuid;
	}

	public DefinitionClient(DefinitionTypeClient definitionType,
			String definition, String description,
			UsersClient usersByCreatedBy, LocationClient locationByCreatedAt,
			LocationClient locationByChangedAt, UsersClient usersByChangedBy,
			Boolean default_, Date dateCreated, Date dateChanged, String uuid) {
		this.definitionType = definitionType;
		this.definition = definition;
		this.description = description;
		this.default_ = default_;
		this.usersByCreatedBy = usersByCreatedBy;
		this.locationByCreatedAt = locationByCreatedAt;
		this.locationByChangedAt = locationByChangedAt;
		this.usersByChangedBy = usersByChangedBy;
		this.dateCreated = dateCreated;
		this.dateChanged = dateChanged;
		this.uuid = uuid;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "definition_id", unique = true, nullable = false)
	public Integer getDefinitionId() {
		return this.definitionId;
	}

	public void setDefinitionId(Integer definitionId) {
		this.definitionId = definitionId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "definition_type_id", nullable = false)
	public DefinitionTypeClient getDefinitionType() {
		return this.definitionType;
	}

	public void setDefinitionType(DefinitionTypeClient definitionType) {
		this.definitionType = definitionType;
	}

	@Column(name = "definition", nullable = false, length = 45)
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by")
	public UsersClient getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(UsersClient usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_at")
	public LocationClient getLocationByCreatedAt() {
		return this.locationByCreatedAt;
	}

	public void setLocationByCreatedAt(LocationClient locationByCreatedAt) {
		this.locationByCreatedAt = locationByCreatedAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "changed_at")
	public LocationClient getLocationByChangedAt() {
		return this.locationByChangedAt;
	}

	public void setLocationByChangedAt(LocationClient locationByChangedAt) {
		this.locationByChangedAt = locationByChangedAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "changed_by")
	public UsersClient getUsersByChangedBy() {
		return this.usersByChangedBy;
	}

	public void setUsersByChangedBy(UsersClient usersByChangedBy) {
		this.usersByChangedBy = usersByChangedBy;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_default")
	public Boolean getDefault_() {
		return this.default_;
	}

	public void setDefault_(Boolean default_) {
		this.default_ = default_;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_changed", length = 19)
	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	@Column(name = "uuid", unique = true, nullable = false, length = 38)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Override
	public String toString() {
		return definitionId + ", " + definitionType.getDefinitionTypeId()
				+ ", " + definition + ", " + description + ", " + default_
				+ ", " + dateCreated + ", " + dateChanged + ", " + uuid;
	}
}
