/*
Copyright(C) 2016 Interactive Health Solutions, Pvt. Ltd.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors.
 */

/**
 * @author owais.hussain@ihsinformatics.com
 */

package com.ihsinformatics.gfatmweb.shared.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

// Generated Dec 9, 2015 9:08:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserLocationId generated by hbm2java
 */
@Embeddable
public class UserLocationIdClient implements java.io.Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = -7626374083706712975L;
	private int userId;
	private int locationId;

	public UserLocationIdClient() {
	}

	public UserLocationIdClient(int userId, int locationId) {
		this.userId = userId;
		this.locationId = locationId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "location_id", nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserLocationIdClient))
			return false;
		UserLocationIdClient castOther = (UserLocationIdClient) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getLocationId() == castOther.getLocationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getLocationId();
		return result;
	}

	@Override
	public String toString() {
		return userId + ", " + locationId;
	}
}
